name: git_watcher
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  args: ^2.4.2
  ansi: ^0.4.2
  cli_util: ^0.4.0
  github: ^9.19.0
  barbecue: ^0.4.0
  path: ^1.8.3
  collection: ^1.17.2
  intl: ^0.18.1
  screwdriver: ^5.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9

executables:
  gitwatcher: git_watcher

scripts: scripts.yaml